TaleLin/lin-cms-spring-boot

src/main/java/io/github/talelin/latticy/common/mybatis/Page.java

采用继承的方式重构 Page 分页对象，减少无用代码
1.解决重写了过时方法的问题
2.修复“因没有修改 hashNext()方法”而可能导致的 bug

refactor(Page): 重构 Page 分页对象

---

src/main/java/io/github/talelin/latticy/module/file/FileProperties.java
src/main/java/io/github/talelin/latticy/service/impl/FileServiceImpl.java

配置信息获取方式从 @Value 修改为使用 FileProperties 实例获取

refactor(Uploader): 重构文件上传配置信息获取方式

---

src/main/java/io/github/talelin/latticy/controller/cms/FileController.java

refactor(FileController): 重构 FileController 接收的参数类型

---

src/main/java/io/github/talelin/latticy/dto/admin/DispatchPermissionsDTO.java
src/main/java/io/github/talelin/latticy/dto/admin/NewGroupDTO.java
src/main/java/io/github/talelin/latticy/dto/admin/RemovePermissionsDTO.java
src/main/java/io/github/talelin/latticy/dto/admin/UpdateUserInfoDTO.java
src/main/java/io/github/talelin/latticy/dto/user/RegisterDTO.java

因核心库已删除 @LongList 注解，所以去除对该注解的使用

refactor(LongList): 去除 @LongList 注解的使用

---

src/main/java/io/github/talelin/latticy/common/util/PageUtil.java
src/main/java/io/github/talelin/latticy/service/UserIdentityService.java
src/main/java/io/github/talelin/latticy/service/impl/UserIdentityServiceImpl.java
src/main/java/io/github/talelin/latticy/vo/PageResponseVO.java
src/main/java/io/github/talelin/latticy/vo/UserInfoVO.java
src/main/java/io/github/talelin/latticy/vo/UserPermissionVO.java

refactor(DataType): 重构所有 id 数据类型

---

src/main/java/io/github/talelin/latticy/LatticyApplication.java
src/main/java/io/github/talelin/latticy/common/configuration/CommonConfiguration.java
src/main/java/io/github/talelin/latticy/module/log/MDCAccessConstant.java
src/main/java/io/github/talelin/latticy/module/log/MDCAccessServletFilter.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

1.将不同级别日志分文件夹输出
2.基于 ServletFliter 实现 Access Log

feat(Logback): 增强 Logback 功能

---

src/main/java/io/github/talelin/latticy/common/enumeration/GroupLevelEnum.java

refactor(GroupLevelEnum): value 变量增加 final 修饰

---

src/main/java/io/github/talelin/latticy/common/aop/ResultAspect.java

refactor(ResultAspect): 重构 ResultAspect 拦截逻辑

---

src/main/java/io/github/talelin/latticy/controller/cms/AdminController.java
src/main/java/io/github/talelin/latticy/service/AdminService.java
src/main/java/io/github/talelin/latticy/service/impl/AdminServiceImpl.java

refactor(AdminService): 修正 getAllStructuralPermissions() 方法名拼写错误

---

pom.xml
src/main/java/io/github/talelin/latticy/common/exception/RestExceptionHandler.java
src/main/java/io/github/talelin/latticy/common/interceptor/AuthorizeVerifyResolverImpl.java
src/main/java/io/github/talelin/latticy/controller/cms/UserController.java
src/main/java/io/github/talelin/latticy/controller/v1/BookController.java
src/main/java/io/github/talelin/latticy/extension/file/LocalUploader.java
src/main/java/io/github/talelin/latticy/module/file/AbstractUploader.java
src/main/java/io/github/talelin/latticy/service/impl/AdminServiceImpl.java
src/main/java/io/github/talelin/latticy/service/impl/GroupServiceImpl.java
src/main/java/io/github/talelin/latticy/service/impl/UserServiceImpl.java

refactor: 将核心库升级到 0.2.0-RC1 版本

---

.github/dependabot.yml

chore: 新增 dependabot 配置文件

---

src/main/java/io/github/talelin/latticy/extension/file/QiniuUploader.java

fix: 修复由于只在 sevlet 加载时获取七牛 token 导致的文件上传时 token 过期的 bug

---

src/test/resources/mpg/templates/premium/controller.java.ftl

feat: 新增高级版代码生成器

---

src/main/java/io/github/talelin/latticy/controller/cms/LogController.java
src/main/java/io/github/talelin/latticy/controller/cms/LogVO.java

fix: 修复 log 查询接口，缺少 time 字段的 bug

---

src/main/java/io/github/talelin/latticy/common/configuration/CommonConfiguration.java

fix(MyBatisPlus): 修复分页失效的问题

---

README.md

chore: 修正README锚点不跳转的问题

---

src/main/java/io/github/talelin/latticy/common/exception/RestExceptionHandler.java

fix:#184 解决异常信息不详细的问题

---

src/main/java/io/github/talelin/latticy/common/configuration/CommonConfiguration.java
src/main/java/io/github/talelin/latticy/common/configuration/CustomServletModelAttributeMethodProcessor.java
src/main/java/io/github/talelin/latticy/common/configuration/CustomServletRequestDataBinder.java
src/main/java/io/github/talelin/latticy/common/configuration/WebConfiguration.java
src/main/java/io/github/talelin/latticy/common/exception/RestExceptionHandler.java
src/main/java/io/github/talelin/latticy/controller/cms/AdminController.java
src/main/java/io/github/talelin/latticy/controller/cms/LogController.java
src/main/java/io/github/talelin/latticy/dto/admin/QueryUsersDTO.java
src/main/java/io/github/talelin/latticy/dto/query/BasePageDTO.java
src/main/java/io/github/talelin/latticy/vo/UnifyResponseVO.java

没有对全部接口做绑定，仅为抛砖引玉
针对异常类中的vo泛型进行了定义

分页查询参数绑定bean（部分），修正mp分页插件的注释错误

---

src/main/java/io/github/talelin/latticy/vo/DeletedVO.java
src/main/java/io/github/talelin/latticy/vo/UpdatedVO.java
src/test/java/io/github/talelin/latticy/controller/cms/AdminControllerTest.java
src/test/java/io/github/talelin/latticy/controller/cms/UserControllerTest.java
src/test/java/io/github/talelin/latticy/controller/v1/BookControllerTest.java
src/test/java/io/github/talelin/latticy/mapper/FileMapperTest.java
src/test/java/io/github/talelin/latticy/mapper/LogMapperTest.java
src/test/java/io/github/talelin/latticy/service/impl/AdminServiceImplTest.java
src/test/java/io/github/talelin/latticy/service/impl/BookServiceImplTest.java
src/test/java/io/github/talelin/latticy/service/impl/GroupServiceImplTest.java

主要是修复test中的各种过期api或复杂写法，以及AdminServiceImplTest.java#updateGroup2中nextInt(100)可能生成的id过小，导致在数据库中查到了对应分组，抛出了AssertionFailedError等问题

fix #223 & test去除deprecated api等问题修复

---

pom.xml
src/main/java/io/github/talelin/latticy/common/configuration/CommonConfiguration.java
src/main/java/io/github/talelin/latticy/mapper/UserGroupMapper.java
src/main/java/io/github/talelin/latticy/service/impl/AdminServiceImpl.java
src/main/java/io/github/talelin/latticy/vo/DeletedVO.java
src/main/java/io/github/talelin/latticy/vo/UpdatedVO.java
src/main/resources/mapper/UserGroupMapper.xml
src/test/java/io/github/talelin/latticy/controller/cms/AdminControllerTest.java
src/test/java/io/github/talelin/latticy/controller/cms/UserControllerTest.java
src/test/java/io/github/talelin/latticy/controller/v1/BookControllerTest.java
src/test/java/io/github/talelin/latticy/mapper/FileMapperTest.java
src/test/java/io/github/talelin/latticy/mapper/LogMapperTest.java
src/test/java/io/github/talelin/latticy/service/impl/AdminServiceImplTest.java
src/test/java/io/github/talelin/latticy/service/impl/BookServiceImplTest.java
src/test/java/io/github/talelin/latticy/service/impl/GroupServiceImplTest.java

Fix/247 & 修复删除权限分组bug

---

src/main/java/io/github/talelin/latticy/common/interceptor/RequestLogInterceptor.java
src/main/java/io/github/talelin/latticy/common/util/IPUtil.java
src/main/java/io/github/talelin/latticy/module/log/MDCAccessServletFilter.java

remote addr经过反代后会变成反代的ip，应当优先判断x-forward-for等请求头

fix: 反代后IP获取错误
